### ISSUE TITLE
Ungregistered alias on MacOS

### ISSUE THREAD

**Issue by mpeters** [iridakos/goto#1]
```
$ goto -r dev /Users/mipeter3/Development/
Alias 'dev' registered successfully.
$ goto dev
goto error: unregistered alias dev
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

This is on Mac OSX 10.13.3

**Comment by mpeters** [comment]
Also, the alias is listed there:
```
$ goto -l
dev /Users/mipeter3/Development
```

But it still can't be found
```
$ goto dev
goto error: unregistered alias dev
```

**Comment by iridakos** [comment]
Thanks for reporting! I will check and get back to you.

**Comment by shnupta** [comment]
I have the exact same issue too. Also on macOS.

**Comment by iridakos** [comment]
With the latest version of the script you should be fine.

@mpeters Can you please close this issue if you check that it works?

Thank you for your feedback :tada:

**Comment by iridakos** [comment]
Side note: there were other problem that were fixed too.

**Comment by shnupta** [comment]
Works perfect for me, and also the auto-completion is working too now!

**Comment by iridakos** [comment]
@shnupta Super!

Issue closed. /cc @mpeters

**Comment by mpeters** [comment]
Just confirming that it works for me now too. Thanks.
