### ISSUE TITLE
host-specific aliases

### ISSUE THREAD

**Issue by dmd** [iridakos/goto#14]
I'd like to be able to specify an alias as only being available on a certain host (i.e., the current one).

**Comment by iridakos** [comment]
Hi @dmd,

Can you please give me a concrete example because I am not sure I understand?

Thank you

**Comment by dmd** [comment]
This is probably too out-of-scope, but I have a shared $HOME (via NFS) across a number of different hosts. I was thinking it would be nice if I could say 'goto blah' on, say, my production server, and it would alias to /opt/mycompany/lib/blah, but if I said 'goto blah' on my development server, it would instead alias to /home/dmd/trunk/lib/blah.

**Comment by dmd** [comment]
I think this is probably too out of scope.

**Comment by iridakos** [comment]
Unfortunately, I think you have to keep different files...

Thank you for reporting!
