### ISSUE TITLE
Make goto ksh compatible

### ISSUE THREAD

**Issue by dmd** [iridakos/goto#27]
The changes needed are:

1. change 'local' to 'typeset'

1. Do not attempt to evaluate (even conditioned out) the _complete functions, which contain some bash/zsh specific syntax.

1. Disable any features (like -p/-o) that don't exist under ksh.

**Comment by dmd** [comment]
Note that `install` mentions putting this into .cshrc and .kshrc.  This script currently works with neither of those shells, so that's a bad idea.

**Comment by dmd** [comment]
I think this is not going to be possible without major ugly changes.

All the code needs to be syntactically correct. There's no getting around it except with `eval` or, for longer code segments, tricks like

```
if [ $is_whatever_shell_understands_blah_blah ]; then
  cat <<EOF > $temp_file
blah blah
blah blah
EOF
  . $temp_file
  rm -f $temp_file
fi
```

It's probably easier to do the port by hand and maintain separate source, if we wanted to do this.

Notes:
- The 'source' command itself is not portable to all KornShells. The portable alternative is . (dot). But that's not the main issue.
- `KSH_VERSION` is not set in `/bin/ksh` on Solaris 10 (e.g., sun22) and AIX (e.g., rs13). That's not the main issue either.
- To resolve the typeset/local business, one could arrange to `alias local=typedef` in KornShells. That by itself is tricky to accomplish; aliases are defined as the source file is read, and so behave unintuitively. 


In functions defined using the `functionname() {` syntax, at least some KornShells don't respect `typedef`; the variables are global. That one we'd have a hard time getting around.

**Comment by dmd** [comment]
If you really wanted to, you could make a ksh version by:

- change 'local' to 'typeset'
- __remove__ all the `_complete*` functions and the registration code
- remove the push/pop functionality

But given how many different incompatible ksh versions there are out there, I'd probably just call this a lost cause, and anyone who wants a ksh version can read this comment and make it themselves, and caveat emptor.

**Comment by iridakos** [comment]
I agree. Thanks for the clarifications.
