### ISSUE TITLE
OSX: The command does not cd to that directory 

### ISSUE THREAD

**Issue by falnatsheh** [iridakos/goto#38]
I tried to install it manually and using brew but both with the same result running OSX `HS 10.13.3`. See below: 
<img width="504" alt="screenshot 2018-05-31 14 03 24" src="https://user-images.githubusercontent.com/702474/40799368-658d90fc-64db-11e8-89f5-b20ed0d8c43e.png">

Let me know if you need any more details.

**Comment by falnatsheh** [comment]
I just realized that the issue related to my current setup. In my dotfile I have `cd() { builtin cd "$@"; ll; } ` which list dir content on `cd` and for some reason when it's there it conflict with `goto`. 

Since this is specific issue with my setup will close the ticket, thank you for your help.

**Comment by iridakos** [comment]
Ok, thank you for reporting ;)
