### ISSUE TITLE
Partly not working on OSX 10.13.6

### ISSUE THREAD

**Issue by AlexNodex** [iridakos/goto#42]
This is partly not working on OSX High Sierra 10.13.6.

I can add an alias, remove an alias but I cannot list aliases nor can I "goto <alias>"

I've uninstalled, reinstalled, rebooted between and after installs, nothing seems to fix it.

**Comment by iridakos** [comment]
Hi @AlexNodex ,

Can you please post the error output of the commands?

**Comment by AlexNodex** [comment]
There is no error output, simply nothing happens.

If I issue `goto --list` I get a full directory listing of the current directory I am in

If I issue `goto <alias>` nothing happens, I stay in my cirrent directory

**Comment by iridakos** [comment]
Is there any chance that you have already an alias for `goto` in your bachrc?

**Comment by AlexNodex** [comment]
That's a possibility, I'll check now

**Comment by iridakos** [comment]
`goto` uses the `cd` command and since you change its functionality it breaks.
Unfortunately I don't have a workaround at the moment.

I'm closing the issue for now and if I find something helpful I will get back to you.

Thanks for reporting.

**Comment by Herzogs** [comment]
I'm sorry but you tried to edit the goto.sh file and in front of the cd command put "builtin"
