### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by goldingdamien** [iridakos/goto#43]
Tried in Git Bash in Windows but nothing happens.
Is Windows supported in any way?

**Comment by iridakos** [comment]
Hi @goldingdamien,
Unfortunately I haven't tested the script in Windows.
I will keep you posted when I find the time to do so.

Thanks for reporting it :)

**Comment by JBlond** [comment]
It works out of the box, at least the script. The installer needs to be changed.
On Windows there is no sudo. And the install path neends to be /usr/share or /usr/local/bin

**Comment by JBlond** [comment]
It might be a trick to use something like

```
if [[ "$OSTYPE" == "msys" ]]; then
```

**Comment by iridakos** [comment]
@JBlond Thank you very much!

I will try to check this as soon as possible. Feel free to submit a pull request in case you have any fix sooner :)

**Comment by JBlond** [comment]
@iridakos See my pull request

**Comment by iridakos** [comment]
@JBlond Thank you very much for contributing! I will check it on my machine and merge it! :+1:

**Comment by JBlond** [comment]
@iridakos Ping

**Comment by iridakos** [comment]
@JBlond Thanks!
