### ISSUE TITLE
Error when using '-l' when there are no aliases yet

### ISSUE THREAD

**Issue by tomwassenberg** [iridakos/goto#5]
When running `goto -l` when you haven't created any aliases yet, the following error is printed: `sed: can't read /home/tom/.goto: No such file or directory`. While correct, it may be nice to catch this and tell the user that there are no aliases presently configured.

Thanks for making this tool btw,  I think it's gonna be saving me quite some time in the long run :)

**Comment by iridakos** [comment]
Thanks for reporting! Wait for it...

**Comment by iridakos** [comment]
Fixed. :D
