### ISSUE TITLE
How to create an alias for goto itself?

### ISSUE THREAD

**Issue by shoda-tibco** [iridakos/goto#53]
`goto` is an awesome tool and I use it heavily. However I would like to alias `goto` itself to something shorter, perhaps `g` or `gt`. However if I do a simple `alias g=goto`, bash completions do not work for the aliased version.

It would be nice if there was an option to install `goto` with an aliased name, or some instructions in the README on how to set up an alias such that completions still work, e.g. by registering the same completion functions for the alias as for `goto`.

**Comment by spezifanta** [comment]
By looking at the code, you should be able to get autocompletion working by just renaming the `goto` executable itself.

**Comment by iridakos** [comment]
Hi @shoda-tibco and thank you :+1: 

I just pushed a new version (1.2.4) and I believe it resolves your issue.

Can you please check it out and let me know if it works on your system? I tested it in Ubuntu under Bash and it works as expected.

**Comment by iridakos** [comment]
@spezifanta Thanks for the info :+1: The new version affects ZSH as well, hope it works there too :crossed_fingers:
