### ISSUE TITLE
Goto breaked after update to 1.2.4

### ISSUE THREAD

**Issue by vanhtuan0409** [iridakos/goto#54]
Hi, I'm glad that this project is still under maintenance
Unfortunately, It gets broken after updating to 1.2.4
The error is: `bad set of key/value pairs for associative array`
Environment: ZSH
Thank a lot for an awesome tool

**Comment by iridakos** [comment]
Hi @vanhtuan0409 and thank you for your kind words!

I just pushed version 1.2.4.1 and I managed to test it in zsh.

Feel free to open the issue if it doesn't work as expected.
