### ISSUE TITLE
Storage of config file should use XDG_CONFIG_HOME if configured

### ISSUE THREAD

**Issue by brennanfee** [iridakos/goto#56]
If the XDG_CONFIG_HOME variable is configured, that should be used as the default storage location (commonly ~/.config).

This has become the newer standard location for "dotfiles" and config files for Linux applications to try keeping the home path cleaner.

Still allowing an override is good, but the default should be changed to be more compliant with the Linux standard.

**Comment by brennanfee** [comment]
I have created a PR for this #57 

Note that my implementation should be documented as a breaking change.  People would need to manually move their $HOME/.goto file to the $HOME/.config/goto file.

If desired a more complex "fallback" mechanism could be implemented but would be slower for each execution of goto.

**Comment by iridakos** [comment]
Thanks again for your time :+1:
