### ISSUE TITLE
source command fails

### ISSUE THREAD

**Issue by ahabra** [iridakos/goto#6]
when I run:
```
source path/to/goto.bash
```
I get this error:
goto.bash:273: command not found: complete

I use a Mac.

**Comment by iridakos** [comment]
Hi @ahabra 

Can you please check [this thread](https://github.com/eddiezane/lunchy/issues/57) and let me know if it fixes your issue?

It has to do with your current macOS setup - missing bash_completion probably.

**Comment by pm190618** [comment]
confirmed that adding the lines:
autoload bashcompinit
bashcompinit
before sourcing goto.bash in ~/.bashrc works like a charm.

**Comment by iridakos** [comment]
@pm190618 Thank you :+1: !

@ahabra I'm closing the issue. If you still can't make it work feel free to reopen it. :crossed_fingers:

**Comment by ahabra** [comment]
@pm190618 Your suggestion fixed the problem. Thank you.
