### ISSUE TITLE
Bug (Minor) (Linux): Does not check for ~/.config directory

### ISSUE THREAD

**Issue by arcanemachine** [iridakos/goto#61]
Just a small bug: The program does not check to make sure the ~/.config directory exists. Until this directory is created, the program will happily report that the shortcut has been created, although it has not.

**Comment by iridakos** [comment]
Hi @arcanemachine and sorry for the late response. I will check it asap, thank you for reporting!

**Comment by iridakos** [comment]
Hi @arcanemachine, this should be fixed with this [PR](https://github.com/iridakos/goto/pull/64).

Thanks for reporting and feel free to re-open the issue in case the problem still exists! :+1:
